### ISSUE TITLE
About popup links to wrong repo

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#12]
The about popup link "open source" links to [that](https://github.com/bernaferrari/CarouselGifViewer) instead of this repo.

**Comment by bernaferrari** [comment]
Lol, now you know where it came from. Will be fixed soon, thanks!!

**Comment by bernaferrari** [comment]
I'm currently thinking about removing swipe to refresh (it already syncs every time the user opens the app). Plus, I might add a manual refresh item on settings. Is that something that you could live with?

**Comment by Madis0** [comment]
Sure, it is not needed that often.

**Comment by bernaferrari** [comment]
Nice! I'm currently refactoring and integrating most of my apps into a 'common' module, so that I avoid duplicate work. New SDK Monitor version coming hopefully soon (nothing new, but I want to integrate crashlytics to catch your crashes and make it easier for me).

**Comment by bernaferrari** [comment]
Fixed.
