### ISSUE TITLE
syncerror

### ISSUE THREAD

**Issue by landingpencil** [bernaferrari/SDKMonitor#13]
Plugin [id: 'com.android.application'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
Open File

**Comment by landingpencil** [comment]
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/pencil/AndroidStudioProjects/SDKMonitor/app/build.gradle.kts' line: 5
Plugin [id: 'com.android.application'] was not found in any of the following sources:

**Comment by bernaferrari** [comment]
Uh oh, I've been making some radical changes and this wasn't supposed to
happen. I'll see here is I forgot to push something, thanks!

**Comment by bernaferrari** [comment]
Hi, could you try again on the last commit? I couldn't find your issue, but there was a build problem when you tried.

**Comment by landingpencil** [comment]
I update Android Studio 3.5 canary 9 then it works well , thinks
