### ISSUE TITLE
Minimum SDK

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#14]
What if the app could also count the minimum SDK, set by a toggle in the settings? 

Could be useful to see how many of user's apps can be used on a older device, such as recommending to a relative.

The colors would be reversed:
- ...-26 as red 
- 25-21 as yellow 
- 20-0 as green

**Comment by bernaferrari** [comment]
It is possible.. the problem is that nowadays a lot of people are doing multiple versions, so this number is not entirely reliable. You might get Youtube for 23+, for 21+ and for 16+.

**Comment by Madis0** [comment]
Indeed, would be pointless if it is not "accurate".
