### ISSUE TITLE
App stores

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#2]
It seems like a great app, but unfortunately it is not in any app stores, which hinders findability, even for developers. Here are some I would suggest, from easiest to hardest:

- [XDA Labs](https://labs.xda-developers.com/)
- [Play Store](https://play.google.com/)
- [F-droid](https://f-droid.org/)

**Comment by bernaferrari** [comment]
Soon. I wanted to play with breaking changes and wait for the first users before putting it there. I think when I implement everything you asked it will be ready for the stores.

**Comment by Poussinou** [comment]
I opened a Request For Packaging on the F-Droid side [here](https://gitlab.com/fdroid/rfp/issues/790). Do not hesitate to join the discussion ;)

**Comment by bernaferrari** [comment]
Yeah, I support it, and I still have no idea what to do to get it included in F-Droid. I don't understand what I need to do.

**Comment by Zebra67** [comment]
Debug application shows when system app enable else not please solve this

**Comment by Madis0** [comment]
@Zebra67 Perhaps you mean #11?

**Comment by Zebra67** [comment]
sorry I tried old version without base view version, in that debugged apps
not showing ,debugged apps only showing when system app toggle is enable

**Comment by bernaferrari** [comment]
I don't understand, is that fixed for you?

**Comment by Zebra67** [comment]
I will try new version then I tell you

**Comment by Zebra67** [comment]
I tried latest version but still not showing Debugged applications please
check

**Comment by bernaferrari** [comment]
You remove it from menu xml and add to settings an item. I'm using navigation library with single activity, so you just need to follow this :

https://developer.android.com/guide/navigation/

**Comment by Zebra67** [comment]
how to call settingsfragment
I tried StartActivity(Mainactivity.class,Settingsfragment.class)
but not work

**Comment by bernaferrari** [comment]
You don't, since all is fragment. You need to add an action on navigation
and then call View.findNavController.navigate(R.id.actionName)

**Comment by Madis0** [comment]
[The app is available in F-Droid 🙂](https://f-droid.org/packages/com.bernaferrari.sdkmonitor/)

**Comment by bernaferrari** [comment]
I didn't know. Thanks for your work. I haven't given much attention on this app and never expect it to have that great of a following!
