### ISSUE TITLE
Themed icon

### ISSUE THREAD

**Issue by w9925** [bernaferrari/SDKMonitor#21]
Please add an themed icon to the app

**Comment by bernaferrari** [comment]
Fixed (finally!!!): https://github.com/bernaferrari/SDKMonitor/releases/tag/0.991

**Comment by bernaferrari** [comment]
Weird. Can you show a screenshot (just to double check)? You meant the monochrome icon, right? Because the other one I already support.

**Comment by bernaferrari** [comment]
I forgot to update the apk compile version (could it be this?) but it is the correct apk
