### ISSUE TITLE
Wrong Android version for Android 12+

### ISSUE THREAD

**Issue by oldherl** [bernaferrari/SDKMonitor#22]
Level 31 and 32 are both for Android 12, so anything later than that is displayed off by one now.

Also it's time to update the threshold for green now.

**Comment by papjul** [comment]
Fixed in a892c45a5358ce74de995db32d83c930777cfc6a

**Comment by oldherl** [comment]
Thanks. Any plan to make a release soon?

**Comment by bernaferrari** [comment]
Absolutely! Just a second.
