### ISSUE TITLE
Upload new app version

### ISSUE THREAD

**Issue by w9925** [bernaferrari/SDKMonitor#27]
I'm not sure if the 2024 update is already working... if so, please upload the compiled apk to github. Thanks for this Important Update 👍

**Comment by bernaferrari** [comment]
oh, I forgot, sorry! Doing it now (will send a second update here).

**Comment by bernaferrari** [comment]
Here it goes! Thanks for the patience: https://github.com/bernaferrari/SDKMonitor/releases/tag/0.99

**Comment by bernaferrari** [comment]
If you need anything, or ever need it updated again, feel free to open another issue! I love when people use and the only way I know people are using is when they complain. Sometimes I forget, but I want the app to always be the best.
