### ISSUE TITLE
Notifications no longer work

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#28]
In v0.99 and 0.991, the notifications no longer work because it is not possible to enable them in system.

Also the auto-update period doesn't seem to save no matter what number or interval you enter.

**Comment by bernaferrari** [comment]
Grrrrrrr oh no. Thanks for still using this app after so many years!

**Comment by bernaferrari** [comment]
@papjul if you want to take a look 👀 else I can probably fix it too

**Comment by papjul** [comment]
Which notifications?

I can see we can't save the period indeed. Not something I use or that I tweaked, so I overlooked that part when testing. I can take a look tomorrow.

**Comment by Madis0** [comment]
There used to be notifications about which recently updated apps bumped the target API. 

I think the system is now requiring notification channels and this app might be lacking them (though I haven't read the code to confirm my assumption).

**Comment by bernaferrari** [comment]
I haven't programmed in Android for 5 years. I'm going to try (and probably fail) to update this project to Compose. Let's see how well it works.

**Comment by papjul** [comment]
Yes, a notification permission is available since Android 13, but I'm surprised it can't even be enabled from settings. I can take a look, but I'm not sure how to trigger the notification to test the use case.

Note: the two issues are unrelated to Compose ;)

**Comment by bernaferrari** [comment]
Oh, I agree, it is more like.. why struggle trying to get databinding/epoxy to work when there is something supposedly better/simpler? Let's see if Claude makes it easy.

**Comment by papjul** [comment]
I pushed a PR for the notifications issue.

Regarding saving background sync preferences, they are no longer saved in `updateSyncInterval()` since b0267f2 from what I can see. I wonder why it was commented during the refactoring?

**Comment by bernaferrari** [comment]
That was 5 years ago. Possibly a mistake. Thanks for all your help!
