### ISSUE TITLE
Highlight bad and good SDKs

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#3]
This app seems to be inspired by [AppChecker](https://play.google.com/store/apps/details?id=com.kroegerama.appchecker). Compared to that, your app unfortunately makes the SDK numbers smaller and in-distinctive (the backgrounds are taken from app icon instead of highlighting the number importance).

I'm not sure how exactly you should do this - categorize, tab, color-code, etc. - but you should separate at least three kinds of apps:

- good - the ones that target 26 or higher (according to Google Play's requirements, increment each year)
- okay - the ones that target 25 or lower, increment by the good value accordingly
- bad - apps that target an API so low that they get a warning on the specific system ([v17 on Pie](https://www.androidpolice.com/2018/03/18/android-p-feature-spotlight-apps-built-android-4-1-lower-may-blocked-running/), [v22 on Q](https://www.xda-developers.com/android-q-warn-apps-target-android-lollipop/)) Should be findable by flag `PLATFORM_MIN_SUPPORTED_TARGET_SDK_VERSION`.

**Comment by bernaferrari** [comment]
Yeah, I didn't know App Checker until a week ago, but now I want this, too. Soon.

**Comment by bernaferrari** [comment]
![screenshot_20190216-134516_sdk monitor](https://user-images.githubusercontent.com/351125/52901969-7ae1ab80-31f1-11e9-91e0-cc818dda7d34.jpg)
Coming soon!

**Comment by bernaferrari** [comment]
Done! Please build the app or download the apk (on readme) and tell me if you like!
