### ISSUE TITLE
History of changes

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#7]
The notifications are good, but it would be even better if the app also logged them. 

Especially in some cases where developers over-estimate their API level readiness and decrease them by a value or two (has happened).

**Comment by bernaferrari** [comment]
When you tap on something, isn't the information shown what you want?

**Comment by Madis0** [comment]
That looks cool, but a global overview would be nice too.

**Comment by bernaferrari** [comment]
Oh, got it. I'll keep in mind for the future. 2.5 weeks now until I get in
vacation.

**Comment by bernaferrari** [comment]
Coming soon! 
![screenshot_20190216-134522_sdk monitor](https://user-images.githubusercontent.com/351125/52901954-4372ff00-31f1-11e9-9d03-e548862aeae6.jpg)

**Comment by bernaferrari** [comment]
Done! Please build the app or download the apk (on readme) and tell me if you like!
